### ISSUE TITLE
undefined is not an object (evaluating 'polygon.locations')

### ISSUE THREAD

**Issue by arnoldas500** [MappedIn/react-native#15]
When using 
         onPolygonClicked={({ polygon }) => {
           setSelectedLocation(polygon.locations[0]);
         }}
getting:
undefined is not an object (evaluating 'polygon.locations')

app is running with expo and using venue: 'green-way-markets', getting error message when I click on any of the points displayed on the map

**Comment by jeresuikkila** [comment]
Hi Arnold

I think we addressed this over other channels but if you have further questions please do not hesitate to email me directly at firstname@mappedin.com.
